### PR TITLE
Enable bitcode for iOS framework

### PR DESCRIPTION
**Pull request by vixentael**
Enable bitcode for iOS framework, which allows other projects to enable bitcode and optimize app size.

* Regenerate framework

* Changes in xcodeproj and script:

   - set ENABLE_BITCODE to `YES`
   - set BITCODE_GENERATION_MODE to `bitcode`

* Update podspec 
   
   - enable bitcode for iOS project
   - increment pod version

* Checks

   - Check existing architectures

```
$ lipo -info OpenSSL-iOS/bin/openssl.framework/openssl 
Architectures in the fat file: OpenSSL-iOS/bin/openssl.framework/openssl are: i386 x86_64 armv7 armv7s arm64 
```

   - Check that framework contains bitcode

```
$ otool -arch arm64 -l OpenSSL-iOS/bin/openssl.framework/openssl | grep LLVM
  segname __LLVM
   segname __LLVM

$ otool -arch armv7 -l OpenSSL-iOS/bin/openssl.framework/openssl | grep LLVM
  segname __LLVM
   segname __LLVM

$ otool -arch armv7s -l OpenSSL-iOS/bin/openssl.framework/openssl | grep LLVM
  segname __LLVM
   segname __LLVM
```

_____________________

I hope these changes are enough to support bitcode :)

I used generated framework in the real project to make sure that it builds and runs on device with enabled bitcode 💪

P.S.
now framework is really 'fat' ~26MB 🤓

### CODE REVIEW

**Comment by vixentael** [comment]
@levigroker 

please take a look! :)

**Comment by levigroker** [comment]
Yes. I'm looking at this now.

**Comment by levigroker** [comment]
Have you tried to integrate the resulting framework into a project, archive it, and export from Xcode? Clang is not happy.

```Failed to verify bitcode in openssl.framework/openssl:
error: Clang option verification failed for bitcode 001 (unrecognized arguments: -disable-llvm-passes)```

**Comment by levigroker** [comment]
Maybe this will help: https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9

**Comment by vixentael** [comment]
I haven't tried archiving the project, just building it for iPhone.

Thank you, I'll take a look

**Comment by vixentael** [comment]
Well, I tried archiving & exporting project with framework linked via CocoaPods. Works well for me on Xcode 9-beta-6. Link to my example project https://www.dropbox.com/s/txc2e1u3f88qxmf/TestFramework.zip?dl=0

@levigroker can you share your project, please?

**Comment by vixentael** [comment]
I did small research :)

It looks that flag `-disable-llvm-passes` is smth new from Xcode9. 

- https://stackoverflow.com/questions/44835255/failed-to-verify-bitcode-unrecognized-arguments-disable-llvm-passes

- https://gist.github.com/anonymous/9690d4d6fc82a1434e03682dacf4f4f2#file-verifier-py-L61

So I've re-built framework with xcode8 and open new PR: https://github.com/levigroker/GRKOpenSSLFramework/pull/4

**Pull request closed without merging**
